model:
  checkpoint: /home/aita4090/zyx/MSIDiff/logs/training_2024_08_26__23_30_43/checkpoints/595000.pt

sample:
  seed: 2024
  num_samples: 100
  num_steps: 1000
  pos_only: False
  center_pos_mode: protein
  sample_num_atoms: prior
